apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ajin-app
  template:
    metadata:
      labels:
        app: ajin-app
    spec:
      containers:
      - name: web-container
        image: ajinb098/project-3:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ajin-service
spec:
  type: NodePort
  selector:
    app: ajin-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30009
